name: Deploy to S3

on:
  push:
    branches:
      - main # Change this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: |
          # Install dependencies for AWS CLI v2
          sudo apt update
          sudo apt install -y unzip curl

          # Download the AWS CLI v2 installation package
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          
          # Unzip the package
          unzip awscliv2.zip
          
          # Install AWS CLI
          sudo ./aws/install

          # Verify the installation
          aws --version

      - name: Deploy to S3
        run: |
          # Sync the files to your S3 bucket
          aws s3 sync ./dist s3://ohmovie2v --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"
